#ifndef QI_GUI_H
#define QI_GUI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 片段样式位（与 qi 侧 `图形.富文本片段` 的样式参数一致）
 */
#define FLAG_BOLD 1

#define FLAG_ITALIC 2

#define FLAG_MONO 4

#define FLAG_STRIKE 8

#define FLAG_UNDERLINE 16

#define FLAG_CODE_BG 32

/**
 * 高亮样式位（与 qi 侧 高亮.qi 的常量一致）
 */
#define HL_HEADING 1

#define HL_BOLD 2

#define HL_ITALIC 4

#define HL_CODE 8

#define HL_LINK 16

#define HL_MARKER 32

#define HL_QUOTE 64

#define HL_BLOCK 128

#define HL_STRIKE 256

#define HL_LIST 512

/**
 * 解码宽度上限。再宽软光栅也画不动，预览栏也用不着
 */
#define MAX_DECODE_WIDTH 960

/**
 * 帧率上限：高帧率素材按 30 抽帧
 */
#define MAX_FPS 30.0

#define AUDIO_RATE 48000

#define AUDIO_CHANNELS 2

/**
 * 库版本（保留供 版本() 使用）
 */
char *qi_gui_version_impl(void);

/**
 * 释放由本库返回的字符串
 *
 * # Safety
 * `s` 必须是空指针，或是本库（`CString::into_raw`）返回、尚未释放过的指针。
 */
void qi_gui_free_string_impl(char *s);

/**
 * 加载音频文件，返回播放器 id（>0 成功，0 失败）。支持 MP3/WAV/FLAC/Vorbis。
 *
 * # Safety
 * `file_path` 必须是空指针，或指向以 NUL 结尾、在调用期间有效的 C 字符串。
 */
uint64_t qi_gui_audio_load_impl(const char *file_path);

/**
 * 播放
 */
void qi_gui_audio_play_impl(uint64_t audio_id);

/**
 * 暂停
 */
void qi_gui_audio_pause_impl(uint64_t audio_id);

/**
 * 停止
 */
void qi_gui_audio_stop_impl(uint64_t audio_id);

/**
 * 设置音量（0.0..1.0）
 */
void qi_gui_audio_set_volume_impl(uint64_t audio_id, float volume);

/**
 * 是否正在播放（1/0）
 */
int32_t qi_gui_audio_is_playing_impl(uint64_t audio_id);

/**
 * 是否播放完成（1/0）
 */
int32_t qi_gui_audio_is_finished_impl(uint64_t audio_id);

/**
 * 释放播放器
 */
void qi_gui_audio_free_impl(uint64_t audio_id);

/**
 * 音频位置(id) → 已播放毫秒
 */
int64_t qi_gui_audio_position_ms_impl(uint64_t audio_id);

/**
 * 音频时长(id) → 总毫秒；格式给不出时长时 0
 */
int64_t qi_gui_audio_duration_ms_impl(uint64_t audio_id);

/**
 * 音频跳到(id, 毫秒) → 1 成功 / 0 失败（已播完的要重新加载才能跳）
 */
int64_t qi_gui_audio_seek_ms_impl(uint64_t audio_id, int64_t ms);

/**
 * 创建 egui 应用窗口，返回句柄（>0 成功，0 失败）
 */
uint64_t qi_gui_egui_app_create_impl(const char *title, uint32_t width, uint32_t height);

/**
 * 帧开始：pump 事件 + begin_pass + 建根 Ui。返回 1=窗口存活，0=已关闭。
 */
int32_t qi_gui_egui_frame_begin_impl(uint64_t app_id);

/**
 * 帧结束：end_pass + tessellate + 光栅化 + present + 限帧
 */
void qi_gui_egui_frame_end_impl(uint64_t app_id);

/**
 * 关闭应用（销毁窗口，释放资源）
 */
void qi_gui_egui_app_close_impl(uint64_t app_id);

/**
 * 滚动开始(id, 高度pt)：固定高度的垂直滚动视口。内容超高时出滚动条，
 * 滚轮悬停滚动。偏移量按 id 持久化在 egui 内存里（跨帧保持）。
 */
void qi_gui_egui_scroll_begin_impl(const char *id, int64_t height);

/**
 * 滚动结束：收内容高度 → 处理滚轮 → 画滚动条 → 光标推进过视口
 */
void qi_gui_egui_scroll_end_impl(void);

/**
 * 折叠开始(标题)：可点开合的分区头。返回 1=展开（子控件会显示）/ 0=收起。
 * 收起时调用方照常写子控件调用也无妨（会落到父 Ui），但推荐用返回值跳过。
 */
int32_t qi_gui_egui_collapse_begin_impl(const char *title);

/**
 * 折叠结束：与 折叠开始 配对；展开时弹出子 Ui 并推进父光标
 */
void qi_gui_egui_collapse_end_impl(void);

/**
 * 普通标签
 */
void qi_gui_egui_label_impl(const char *text);

/**
 * 大号标题
 */
void qi_gui_egui_heading_impl(const char *text);

/**
 * 彩色标签
 */
void qi_gui_egui_colored_label_impl(const char *text, int64_t r, int64_t g, int64_t b);

/**
 * 按钮：返回本帧是否被点击（1/0）
 */
int32_t qi_gui_egui_button_impl(const char *text);

/**
 * 单行输入框：传入当前值，返回编辑后的新值
 */
const char *qi_gui_egui_text_edit_impl(const char *id, const char *value);

/**
 * 多行输入框
 */
const char *qi_gui_egui_text_edit_multiline_impl(const char *id, const char *value);

/**
 * 整数滑条：返回新值
 */
int64_t qi_gui_egui_slider_impl(const char *_id, int64_t cur, int64_t min, int64_t max);

/**
 * 复选框：返回新的勾选状态（1/0）
 */
int32_t qi_gui_egui_checkbox_impl(const char *_id, const char *text, int32_t cur);

/**
 * 下拉选择：options 为 CSV（逗号分隔），cur 为当前序号，返回新序号
 */
int64_t qi_gui_egui_combo_impl(const char *id, const char *options_csv, int64_t cur);

/**
 * 分隔线
 */
void qi_gui_egui_separator_impl(void);

/**
 * 空行（纵向间距）
 */
void qi_gui_egui_space_impl(void);

/**
 * 水平布局开始
 */
void qi_gui_egui_horizontal_begin_impl(void);

/**
 * 水平布局结束
 */
void qi_gui_egui_horizontal_end_impl(void);

/**
 * 分组开始（带标题的边框容器）
 */
void qi_gui_egui_group_begin_impl(const char *title);

/**
 * 分组结束
 */
void qi_gui_egui_group_end_impl(void);

/**
 * 进度条：percent 0..100
 */
void qi_gui_egui_progress_impl(int64_t percent);

/**
 * 折线图：id 标识，values 为 CSV 数值，宽高（点）。用于画损失曲线等。
 */
void qi_gui_egui_plot_impl(const char *id, const char *values_csv, int64_t width, int64_t height);

/**
 * 消息弹窗：浮动窗口显示文本（需每帧调用以保持显示）
 */
void qi_gui_egui_message_impl(const char *text);

/**
 * 画布开始(id, 宽, 高)：在当前 Ui 占一块定尺寸自绘区。id 目前仅作语义标注。
 */
void qi_gui_egui_canvas_begin_impl(const char *_id,
                                   int64_t width,
                                   int64_t height);

/**
 * 画布结束()
 */
void qi_gui_egui_canvas_end_impl(void);

/**
 * 画布矩形(x, y, 宽, 高, r, g, b)：填充矩形，坐标为画布局部坐标
 */
void qi_gui_egui_canvas_rect_impl(int64_t x,
                                  int64_t y,
                                  int64_t w,
                                  int64_t h,
                                  int64_t r,
                                  int64_t g,
                                  int64_t b);

/**
 * 画布圆(x, y, 半径, r, g, b)：填充圆，(x,y) 为圆心的画布局部坐标
 */
void qi_gui_egui_canvas_circle_impl(int64_t x,
                                    int64_t y,
                                    int64_t radius,
                                    int64_t r,
                                    int64_t g,
                                    int64_t b);

/**
 * 画布线(x1, y1, x2, y2, 粗, r, g, b)：线段，端点为画布局部坐标
 */
void qi_gui_egui_canvas_line_impl(int64_t x1,
                                  int64_t y1,
                                  int64_t x2,
                                  int64_t y2,
                                  int64_t width,
                                  int64_t r,
                                  int64_t g,
                                  int64_t b);

/**
 * 画布文本(x, y, 文本, 字号, r, g, b)：左上对齐绘制文本，(x,y) 为局部坐标
 */
void qi_gui_egui_canvas_text_impl(int64_t x,
                                  int64_t y,
                                  const char *text,
                                  int64_t size,
                                  int64_t r,
                                  int64_t g,
                                  int64_t b);

/**
 * 画布点击() → 整数：本帧画布是否被点击（1/0）
 */
int64_t qi_gui_egui_canvas_clicked_impl(void);

/**
 * 画布鼠标X() → 整数：鼠标在画布内的局部 X（无悬停返回 -1）
 */
int64_t qi_gui_egui_canvas_mouse_x_impl(void);

/**
 * 画布鼠标Y() → 整数：鼠标在画布内的局部 Y（无悬停返回 -1）
 */
int64_t qi_gui_egui_canvas_mouse_y_impl(void);

/**
 * 富文本开始()：开始拼一行
 */
void qi_gui_egui_rich_begin_impl(void);

/**
 * 富文本片段(文本, 字号, 样式位, 颜色)：字号 ≤0 = 正文字号；颜色 <0 = 主题文字色
 */
void qi_gui_egui_rich_span_impl(const char *text,
                                int64_t size,
                                int64_t flags,
                                int64_t color);

/**
 * 富文本结束(缩进, 竖线)：整行按可用宽度折行后放下。缩进单位是像素；
 * 竖线=1 时在缩进区画一条引用竖线（Markdown 的 > 引用）。
 */
void qi_gui_egui_rich_end_impl(int64_t indent, int64_t bar);

/**
 * 代码块(文本, 字号)：等宽 + 底色框，占满可用宽度；字号 <=0 用等宽默认字号
 */
void qi_gui_egui_code_block_impl(const char *text,
                                 int64_t size);

/**
 * 分栏开始(左栏千分比)：把剩余区域左右分成两栏（100–900‰），先进左栏
 */
void qi_gui_egui_columns_begin_impl(int64_t left_permille);

/**
 * 分栏下一栏()：从左栏切到右栏
 */
void qi_gui_egui_columns_next_impl(void);

/**
 * 分栏结束()：收起当前栏，父光标推进过整个分栏区域
 */
void qi_gui_egui_columns_end_impl(void);

/**
 * 编辑区(id, 当前值, 等宽, 字号) → 新值：撑满剩余区域的多行输入，自带纵向滚动。
 * Tab 键插入制表符而不是切焦点。调用后可用 编辑区光标() 取光标位置。
 */
const char *qi_gui_egui_editor_impl(const char *id,
                                    const char *value,
                                    int64_t mono,
                                    int64_t size);

/**
 * 编辑区光标() → 最近一次 编辑区 调用后的光标字符下标；没有光标时 -1
 */
int64_t qi_gui_egui_editor_cursor_impl(void);

/**
 * 编辑区光标行() → 光标在第几行（按换行分，从 1 起，折行不算）；没有光标时 -1。
 * 状态栏「行:列」直接用它，qi 不必为了数行把正文切开
 */
int64_t qi_gui_egui_editor_cursor_row_impl(void);

/**
 * 编辑区光标列() → 光标是本行第几个字符（从 1 起）；没有光标时 -1
 */
int64_t qi_gui_egui_editor_cursor_col_impl(void);

/**
 * 设置编辑区光标(id, 字符下标)：下一帧生效（协同编辑合入远端改动后挪光标用）
 */
void qi_gui_egui_editor_set_cursor_impl(const char *id,
                                        int64_t pos);

/**
 * 组合键(键名, 上档) → 1/0：Cmd（macOS）/ Ctrl（其它）+ 键本帧刚按下。
 * 上档=1 要求同时按 Shift，上档=0 要求没按 Shift（⌘S 与 ⇧⌘S 互不串）。
 * 命中即消费该按键事件，不会再落进输入框。
 */
int64_t qi_gui_egui_shortcut_impl(const char *name, int64_t shift);

/**
 * 设置窗口边距(像素)：根区域离窗口边缘多远（默认 10；做贴边的工具栏/状态栏设 0）
 */
void qi_gui_egui_window_margin_impl(int64_t px);

/**
 * 设置外观(底色, 文字, 弱文字, 强调, 边框, 字号)：一次给全套浅/深色配色和基准字号。
 * 颜色是打包整数 r*65536+g*256+b。代码底色、斑马纹、悬停底色都从底色和文字按比例混出来；
 * 按钮平时没有底，悬停才显出来（工具栏那种扁平按钮）。每帧调用也无妨。
 */
void qi_gui_egui_set_appearance_impl(int64_t bg,
                                     int64_t text,
                                     int64_t weak,
                                     int64_t accent,
                                     int64_t border,
                                     int64_t size);

/**
 * 弱标签(文本)：次要信息（状态栏、提示）用的浅色文字
 */
void qi_gui_egui_weak_label_impl(const char *text);

/**
 * 空白(像素)：沿当前布局方向留一段空
 */
void qi_gui_egui_add_space_impl(int64_t px);

/**
 * 区域开始(高度, 内边距, 背景色, 最大宽)：
 * - 高度 >0 定高；0 随内容长；-1 撑满剩余高度；-(N+1) 撑满但底下让出 N 像素
 *   （给状态栏留地方）。在滚动区里剩余高度无限，撑满也按随内容长处理
 * - 背景色 <0 不画底
 * - 最大宽 >0 且可用宽度更宽时，内容区按最大宽水平居中（阅读栏）
 */
void qi_gui_egui_region_begin_impl(int64_t height,
                                   int64_t pad,
                                   int64_t bg,
                                   int64_t max_width);

/**
 * 区域结束()：补画底色，父光标推进过整个区域
 */
void qi_gui_egui_region_end_impl(void);

/**
 * 右对齐开始()：在当前这一行剩下的宽度里从右往左排（先写的在最右）
 */
void qi_gui_egui_right_begin_impl(void);

/**
 * 右对齐结束()
 */
void qi_gui_egui_right_end_impl(void);

/**
 * 适应图片(路径, 最大宽) → 1 显示了 / 0 读不了：按原图比例缩到可用宽度
 * （再不超过最大宽，<=0 不限），不放大；圆角
 */
int64_t qi_gui_egui_image_fit_impl(const char *path, int64_t max_width);

/**
 * 进度拖条(id, 千分比, 宽) → 本帧被点/拖到的千分比，没动返回 -1。
 * 细轨 + 强调色已走部分 + 圆头，音视频播放进度用。宽 <=0 占满可用宽度
 */
int64_t qi_gui_egui_seek_bar_impl(const char *_id, int64_t permille, int64_t width);

/**
 * 拖入文件() → 这一帧拖进窗口的文件路径，多个用换行分开；没有则空串
 */
const char *qi_gui_egui_dropped_files_impl(void);

/**
 * 托管编辑区(id, 等宽, 字号) → 版本：撑满剩余区域的多行输入，自带纵向滚动。
 * 正文在 Rust 这边，内容每改一次版本 +1。调用后 编辑区光标() 照常可用。
 */
int64_t qi_gui_egui_editor_managed_impl(const char *id,
                                        int64_t mono,
                                        int64_t size);

/**
 * 设置编辑区文本(id, 文本)：整篇换掉（打开文件、新建、程序插入内容），版本 +1，高亮清空
 */
void qi_gui_egui_editor_set_text_impl(const char *id,
                                      const char *text);

/**
 * 编辑区文本(id) → 当前正文（只在版本变了时取）
 */
const char *qi_gui_egui_editor_text_impl(const char *id);

/**
 * 编辑区版本(id) → 内容版本号；没建过的编辑区返回 0
 */
int64_t qi_gui_egui_editor_version_impl(const char *id);

/**
 * 设置编辑区高亮(id, "起,止,样式;…")：对着当前正文算的字节区间；空串 = 不高亮。
 * 跟正文改动后挪过位的旧区间一模一样时什么都不做（不重排）
 */
void qi_gui_egui_editor_set_highlight_impl(const char *id,
                                           const char *spec);

/**
 * 设置高亮颜色(样式位, 颜色)：覆盖某个样式的颜色；颜色 <0 恢复从外观派生的默认色
 */
void qi_gui_egui_set_highlight_color_impl(int64_t bits,
                                          int64_t color);

/**
 * 按键按住(键名) → 1/0：这一帧该键是否处于按下状态（持续触发，适合移动）
 */
int64_t qi_gui_egui_key_down_impl(const char *name);

/**
 * 按键刚按(键名) → 1/0：这一帧刚按下的边沿（适合跳跃 / 开火 / 切换）
 */
int64_t qi_gui_egui_key_pressed_impl(const char *name);

/**
 * 任意键刚按() → 1/0：本帧有任何键刚按下（"按任意键开始"）
 */
int64_t qi_gui_egui_any_key_pressed_impl(void);

/**
 * 画布图片(路径, x, y, 宽, 高)：左上角对齐，拉伸到给定宽高。
 * 宽或高传 <=0 时按图片原始尺寸的比例补齐；两个都 <=0 就用原始尺寸。
 */
void qi_gui_egui_canvas_image_impl(const char *path,
                                   int64_t x,
                                   int64_t y,
                                   int64_t width,
                                   int64_t height);

/**
 * 画布图片旋转(路径, 中心x, 中心y, 宽, 高, 角度)：绕**中心**旋转，角度制，正数顺时针。
 * 做转向的小车 / 朝鼠标的飞机就用它。
 */
void qi_gui_egui_canvas_image_rotated_impl(const char *path,
                                           int64_t cx,
                                           int64_t cy,
                                           int64_t width,
                                           int64_t height,
                                           int64_t degrees);

/**
 * 画布图片翻转(路径, x, y, 宽, 高, 水平翻)：水平翻 != 0 时左右镜像。
 * 角色向左走时翻一下，就不用为左右各画一张图。
 */
void qi_gui_egui_canvas_image_flipped_impl(const char *path,
                                           int64_t x,
                                           int64_t y,
                                           int64_t width,
                                           int64_t height,
                                           int64_t flip_h);

/**
 * 图片宽(路径) → 整数：原始像素宽。读不到返回 0（等比缩放前先判一下就不会除零）。
 */
int64_t qi_gui_egui_image_width_impl(const char *path);

/**
 * 图片高(路径) → 整数：原始像素高。读不到返回 0。
 */
int64_t qi_gui_egui_image_height_impl(const char *path);

/**
 * 供 Qi 侧探测精灵层是否可用（返回批次号）
 */
int64_t qi_gui_egui_sprite_version_impl(void);

/**
 * 本机有没有 ffmpeg / ffprobe
 */
int64_t qi_gui_egui_video_available_impl(void);

/**
 * 视频加载(路径) → 句柄；没装 ffmpeg、文件打不开或没有画面都返回 0。
 * 加载后不播放，但会马上解出第一帧当封面
 */
uint64_t qi_gui_egui_video_load_impl(const char *path);

/**
 * 视频画(句柄, 最大宽) → 1 本帧画面被点了 / 0。按比例占满可用宽度（再不超过最大宽，
 * <=0 不限）；还没解出第一帧时画一块同尺寸的深色底，排版不跳
 */
int64_t qi_gui_egui_video_draw_impl(uint64_t id,
                                    int64_t max_width);

void qi_gui_egui_video_play_impl(uint64_t id);

void qi_gui_egui_video_pause_impl(uint64_t id);

/**
 * 视频跳到(句柄, 毫秒)：播放中跳过去接着放，暂停中跳过去显示那一帧
 */
void qi_gui_egui_video_seek_impl(uint64_t id, int64_t ms);

int64_t qi_gui_egui_video_position_impl(uint64_t id);

int64_t qi_gui_egui_video_duration_impl(uint64_t id);

/**
 * 视频播放中(句柄) → 1/0；放到头自动停，返回 0
 */
int64_t qi_gui_egui_video_playing_impl(uint64_t id);

void qi_gui_egui_video_free_impl(uint64_t id);

/**
 * 单选按钮：selected=当前是否选中，返回 1=本帧被点击（调用方据此切换组内序号）
 */
int32_t qi_gui_egui_radio_impl(const char *text,
                               int32_t selected);

/**
 * 可选中列表项（整行高亮）：返回 1=本帧被点击
 */
int32_t qi_gui_egui_selectable_impl(const char *text, int32_t selected);

/**
 * 数字输入（拖拽/双击编辑的整数框）：返回新值
 */
int64_t qi_gui_egui_drag_value_impl(const char *_id, int64_t cur);

/**
 * 浮点滑条：返回新值
 */
double qi_gui_egui_slider_f64_impl(const char *_id, double cur, double min, double max);

/**
 * 超链接：点击用系统浏览器打开（经 egui-winit 的 open_url 平台输出）
 */
void qi_gui_egui_hyperlink_impl(const char *text, const char *url);

/**
 * 带悬浮提示的标签：鼠标悬停显示气泡
 */
void qi_gui_egui_label_tip_impl(const char *text, const char *tip);

/**
 * 只读表格：表头 CSV（逗号分列），数据行以 '\n' 分行、逗号分列。斑马纹。
 */
void qi_gui_egui_table_impl(const char *id,
                            const char *headers_csv,
                            const char *rows_data);

/**
 * 柱状图：values 为 CSV 数值；宽高（点，0=自适应）
 */
void qi_gui_egui_bar_chart_impl(const char *id,
                                const char *values_csv,
                                int64_t width,
                                int64_t height);

/**
 * 图片显示(路径, 宽, 高)：首次加载解码并缓存为纹理（png/jpg 等），之后直接画。
 * 宽/高传 0 = 用图片原始尺寸。加载失败画一行错误标签（不崩）。
 */
void qi_gui_egui_image_impl(const char *path,
                            int64_t width,
                            int64_t height);

/**
 * 设置主题：1=深色，0=浅色。任意时刻可调（含帧内）。
 */
void qi_gui_egui_set_theme_impl(int32_t dark);

/**
 * 界面缩放：百分比（100=原始，125=放大 1.25 倍…），夹在 50..300
 */
void qi_gui_egui_set_zoom_impl(int64_t percent);

/**
 * 设置窗口标题（运行中随时改）
 */
void qi_gui_egui_window_title_impl(uint64_t app_id, const char *title);

/**
 * 供 Qi 侧探测本批控件是否可用（返回批次号）
 */
int64_t qi_gui_egui_widgets2_version_impl(void);

/**
 * 选择打开文件(标题, 扩展名过滤) → 路径，取消返回空串
 */
const char *qi_gui_dialog_open_file_impl(const char *title, const char *filters);

/**
 * 选择保存文件(标题, 默认名) → 路径，取消返回空串。默认名可以带目录，
 * 带目录时对话框从那个目录开始
 */
const char *qi_gui_dialog_save_file_impl(const char *title,
                                         const char *default_name);

/**
 * 选择文件夹(标题) → 路径，取消返回空串
 */
const char *qi_gui_dialog_pick_folder_impl(const char *title);

/**
 * 菜单添加(菜单名, 项名, 快捷键) → 编号（>0）；本平台没有原生菜单返回 0
 */
int64_t qi_gui_menu_add_impl(const char *menu,
                             const char *item,
                             const char *accel);

/**
 * 菜单分隔线(菜单名)
 */
void qi_gui_menu_separator_impl(const char *menu);

/**
 * 菜单添加编辑项(菜单名) → 1 / 0（本平台没有原生菜单）
 */
int64_t qi_gui_menu_add_edit_impl(const char *menu);

/**
 * 菜单被点() → 编号，没有返回 0
 */
int64_t qi_gui_menu_clicked_impl(void);

#endif  /* QI_GUI_H */
