#ifndef QI_GUI_H
#define QI_GUI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 库版本（保留供 版本() 使用）
 */
char *qi_gui_version_impl(void);

/**
 * 释放由本库返回的字符串
 */
void qi_gui_free_string_impl(char *s);

/**
 * 加载音频文件，返回播放器 id（>0 成功，0 失败）。支持 MP3/WAV/FLAC/Vorbis。
 */
uint64_t qi_gui_audio_load_impl(const char *file_path);

/**
 * 播放
 */
void qi_gui_audio_play_impl(uint64_t audio_id);

/**
 * 暂停
 */
void qi_gui_audio_pause_impl(uint64_t audio_id);

/**
 * 停止
 */
void qi_gui_audio_stop_impl(uint64_t audio_id);

/**
 * 设置音量（0.0..1.0）
 */
void qi_gui_audio_set_volume_impl(uint64_t audio_id, float volume);

/**
 * 是否正在播放（1/0）
 */
int32_t qi_gui_audio_is_playing_impl(uint64_t audio_id);

/**
 * 是否播放完成（1/0）
 */
int32_t qi_gui_audio_is_finished_impl(uint64_t audio_id);

/**
 * 释放播放器
 */
void qi_gui_audio_free_impl(uint64_t audio_id);

/**
 * 创建 egui 应用窗口，返回句柄（>0 成功，0 失败）
 */
uint64_t qi_gui_egui_app_create_impl(const char *title, uint32_t width, uint32_t height);

/**
 * 帧开始：pump 事件 + begin_pass + 建根 Ui。返回 1=窗口存活，0=已关闭。
 */
int32_t qi_gui_egui_frame_begin_impl(uint64_t app_id);

/**
 * 帧结束：end_pass + tessellate + 光栅化 + present + 限帧
 */
void qi_gui_egui_frame_end_impl(uint64_t app_id);

/**
 * 关闭应用（销毁窗口，释放资源）
 */
void qi_gui_egui_app_close_impl(uint64_t app_id);

/**
 * 滚动开始(id, 高度pt)：固定高度的垂直滚动视口。内容超高时出滚动条，
 * 滚轮悬停滚动。偏移量按 id 持久化在 egui 内存里（跨帧保持）。
 */
void qi_gui_egui_scroll_begin_impl(const char *id, int64_t height);

/**
 * 滚动结束：收内容高度 → 处理滚轮 → 画滚动条 → 光标推进过视口
 */
void qi_gui_egui_scroll_end_impl(void);

/**
 * 折叠开始(标题)：可点开合的分区头。返回 1=展开（子控件会显示）/ 0=收起。
 * 收起时调用方照常写子控件调用也无妨（会落到父 Ui），但推荐用返回值跳过。
 */
int32_t qi_gui_egui_collapse_begin_impl(const char *title);

/**
 * 折叠结束：与 折叠开始 配对；展开时弹出子 Ui 并推进父光标
 */
void qi_gui_egui_collapse_end_impl(void);

/**
 * 普通标签
 */
void qi_gui_egui_label_impl(const char *text);

/**
 * 大号标题
 */
void qi_gui_egui_heading_impl(const char *text);

/**
 * 彩色标签
 */
void qi_gui_egui_colored_label_impl(const char *text, int64_t r, int64_t g, int64_t b);

/**
 * 按钮：返回本帧是否被点击（1/0）
 */
int32_t qi_gui_egui_button_impl(const char *text);

/**
 * 单行输入框：传入当前值，返回编辑后的新值
 */
const char *qi_gui_egui_text_edit_impl(const char *id, const char *value);

/**
 * 多行输入框
 */
const char *qi_gui_egui_text_edit_multiline_impl(const char *id, const char *value);

/**
 * 整数滑条：返回新值
 */
int64_t qi_gui_egui_slider_impl(const char *_id, int64_t cur, int64_t min, int64_t max);

/**
 * 复选框：返回新的勾选状态（1/0）
 */
int32_t qi_gui_egui_checkbox_impl(const char *_id, const char *text, int32_t cur);

/**
 * 下拉选择：options 为 CSV（逗号分隔），cur 为当前序号，返回新序号
 */
int64_t qi_gui_egui_combo_impl(const char *id, const char *options_csv, int64_t cur);

/**
 * 分隔线
 */
void qi_gui_egui_separator_impl(void);

/**
 * 空行（纵向间距）
 */
void qi_gui_egui_space_impl(void);

/**
 * 水平布局开始
 */
void qi_gui_egui_horizontal_begin_impl(void);

/**
 * 水平布局结束
 */
void qi_gui_egui_horizontal_end_impl(void);

/**
 * 分组开始（带标题的边框容器）
 */
void qi_gui_egui_group_begin_impl(const char *title);

/**
 * 分组结束
 */
void qi_gui_egui_group_end_impl(void);

/**
 * 进度条：percent 0..100
 */
void qi_gui_egui_progress_impl(int64_t percent);

/**
 * 折线图：id 标识，values 为 CSV 数值，宽高（点）。用于画损失曲线等。
 */
void qi_gui_egui_plot_impl(const char *id, const char *values_csv, int64_t width, int64_t height);

/**
 * 消息弹窗：浮动窗口显示文本（需每帧调用以保持显示）
 */
void qi_gui_egui_message_impl(const char *text);

/**
 * 画布开始(id, 宽, 高)：在当前 Ui 占一块定尺寸自绘区。id 目前仅作语义标注。
 */
void qi_gui_egui_canvas_begin_impl(const char *_id,
                                   int64_t width,
                                   int64_t height);

/**
 * 画布结束()
 */
void qi_gui_egui_canvas_end_impl(void);

/**
 * 画布矩形(x, y, 宽, 高, r, g, b)：填充矩形，坐标为画布局部坐标
 */
void qi_gui_egui_canvas_rect_impl(int64_t x,
                                  int64_t y,
                                  int64_t w,
                                  int64_t h,
                                  int64_t r,
                                  int64_t g,
                                  int64_t b);

/**
 * 画布圆(x, y, 半径, r, g, b)：填充圆，(x,y) 为圆心的画布局部坐标
 */
void qi_gui_egui_canvas_circle_impl(int64_t x,
                                    int64_t y,
                                    int64_t radius,
                                    int64_t r,
                                    int64_t g,
                                    int64_t b);

/**
 * 画布线(x1, y1, x2, y2, 粗, r, g, b)：线段，端点为画布局部坐标
 */
void qi_gui_egui_canvas_line_impl(int64_t x1,
                                  int64_t y1,
                                  int64_t x2,
                                  int64_t y2,
                                  int64_t width,
                                  int64_t r,
                                  int64_t g,
                                  int64_t b);

/**
 * 画布文本(x, y, 文本, 字号, r, g, b)：左上对齐绘制文本，(x,y) 为局部坐标
 */
void qi_gui_egui_canvas_text_impl(int64_t x,
                                  int64_t y,
                                  const char *text,
                                  int64_t size,
                                  int64_t r,
                                  int64_t g,
                                  int64_t b);

/**
 * 画布点击() → 整数：本帧画布是否被点击（1/0）
 */
int64_t qi_gui_egui_canvas_clicked_impl(void);

/**
 * 画布鼠标X() → 整数：鼠标在画布内的局部 X（无悬停返回 -1）
 */
int64_t qi_gui_egui_canvas_mouse_x_impl(void);

/**
 * 画布鼠标Y() → 整数：鼠标在画布内的局部 Y（无悬停返回 -1）
 */
int64_t qi_gui_egui_canvas_mouse_y_impl(void);

/**
 * 单选按钮：selected=当前是否选中，返回 1=本帧被点击（调用方据此切换组内序号）
 */
int32_t qi_gui_egui_radio_impl(const char *text,
                               int32_t selected);

/**
 * 可选中列表项（整行高亮）：返回 1=本帧被点击
 */
int32_t qi_gui_egui_selectable_impl(const char *text, int32_t selected);

/**
 * 数字输入（拖拽/双击编辑的整数框）：返回新值
 */
int64_t qi_gui_egui_drag_value_impl(const char *_id, int64_t cur);

/**
 * 浮点滑条：返回新值
 */
double qi_gui_egui_slider_f64_impl(const char *_id, double cur, double min, double max);

/**
 * 超链接：点击用系统浏览器打开（经 egui-winit 的 open_url 平台输出）
 */
void qi_gui_egui_hyperlink_impl(const char *text, const char *url);

/**
 * 带悬浮提示的标签：鼠标悬停显示气泡
 */
void qi_gui_egui_label_tip_impl(const char *text, const char *tip);

/**
 * 只读表格：表头 CSV（逗号分列），数据行以 '\n' 分行、逗号分列。斑马纹。
 */
void qi_gui_egui_table_impl(const char *id,
                            const char *headers_csv,
                            const char *rows_data);

/**
 * 柱状图：values 为 CSV 数值；宽高（点，0=自适应）
 */
void qi_gui_egui_bar_chart_impl(const char *id,
                                const char *values_csv,
                                int64_t width,
                                int64_t height);

/**
 * 图片显示(路径, 宽, 高)：首次加载解码并缓存为纹理（png/jpg 等），之后直接画。
 * 宽/高传 0 = 用图片原始尺寸。加载失败画一行错误标签（不崩）。
 */
void qi_gui_egui_image_impl(const char *path,
                            int64_t width,
                            int64_t height);

/**
 * 设置主题：1=深色，0=浅色。任意时刻可调（含帧内）。
 */
void qi_gui_egui_set_theme_impl(int32_t dark);

/**
 * 界面缩放：百分比（100=原始，125=放大 1.25 倍…），夹在 50..300
 */
void qi_gui_egui_set_zoom_impl(int64_t percent);

/**
 * 设置窗口标题（运行中随时改）
 */
void qi_gui_egui_window_title_impl(uint64_t app_id, const char *title);

/**
 * 供 Qi 侧探测本批控件是否可用（返回批次号）
 */
int64_t qi_gui_egui_widgets2_version_impl(void);

#endif  /* QI_GUI_H */
