#ifndef QI_GUI_H
#define QI_GUI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Event callback function type
 * Parameters: window_id, event_type, param1, param2
 * event_type:
 *   0=CloseRequested
 *   1=Resized(width, height)
 *   2=KeyPressed(keycode, modifiers)
 *       - param1 (keycode): Key code (character codes for A-Z, 0-9 or special key codes)
 *       - param2 (modifiers): Bitmask - Bit0:Shift, Bit1:Ctrl, Bit2:Alt, Bit3:Meta/Command
 *   3=MouseClicked(button, state)
 *   4=MouseMoved(x, y)
 *   5=MouseWheel(delta_x, delta_y)
 */
typedef void (*EventCallback)(uint64_t, int32_t, int64_t, int64_t);

/**
 * Create a window (queued until run is called)
 * Returns a window ID (non-zero on success, 0 on failure)
 */
uint64_t qi_gui_create_window_impl(const char *title, uint32_t width, uint32_t height);

/**
 * Destroy a window (currently a no-op in lazy mode)
 */
void qi_gui_destroy_window_impl(uint64_t window_id);

/**
 * Set window title (updates queued window or title map)
 */
void qi_gui_set_title_impl(uint64_t window_id, const char *title);

/**
 * Get window title
 */
char *qi_gui_get_title_impl(uint64_t window_id);

/**
 * Show window (no-op in current implementation)
 */
void qi_gui_show_window_impl(uint64_t _window_id);

/**
 * Hide window (no-op in current implementation)
 */
void qi_gui_hide_window_impl(uint64_t _window_id);

/**
 * Check if window is visible
 */
int32_t qi_gui_is_visible_impl(uint64_t window_id);

/**
 * Set event callback for a window
 * callback signature: fn(window_id: u64, event_type: i32, param1: i64, param2: i64)
 * event_type: 0=CloseRequested, 1=Resized(width, height), 2=KeyPressed(keycode), 3=MouseClicked(x, y)
 */
void qi_gui_set_event_callback_impl(uint64_t window_id,
                                    EventCallback callback);

/**
 * Enable default event printing for a window (prints events to console)
 */
void qi_gui_enable_event_printing_impl(uint64_t window_id);

/**
 * Get window X position
 */
int64_t qi_gui_get_position_x_impl(uint64_t window_id);

/**
 * Get window Y position
 */
int64_t qi_gui_get_position_y_impl(uint64_t window_id);

/**
 * Set window position
 */
void qi_gui_set_position_impl(uint64_t window_id, int32_t x, int32_t y);

/**
 * Get window width
 */
int64_t qi_gui_get_width_impl(uint64_t window_id);

/**
 * Get window height
 */
int64_t qi_gui_get_height_impl(uint64_t window_id);

/**
 * Set window size
 */
void qi_gui_set_size_impl(uint64_t window_id, uint32_t width, uint32_t height);

/**
 * Run the event loop (creates all pending windows and starts event processing)
 */
void qi_gui_run_impl(void);

/**
 * Free a string allocated by this library
 */
void qi_gui_free_string_impl(char *s);

/**
 * Get library version
 */
char *qi_gui_version_impl(void);

/**
 * Load an audio file and create a player
 * Returns audio player ID (> 0) on success, 0 on failure
 * Supports: MP3, WAV, FLAC, Vorbis
 */
uint64_t qi_gui_audio_load_impl(const char *file_path);

/**
 * Play audio
 */
void qi_gui_audio_play_impl(uint64_t audio_id);

/**
 * Pause audio
 */
void qi_gui_audio_pause_impl(uint64_t audio_id);

/**
 * Stop audio
 */
void qi_gui_audio_stop_impl(uint64_t audio_id);

/**
 * Set audio volume (0.0 to 1.0)
 */
void qi_gui_audio_set_volume_impl(uint64_t audio_id, float volume);

/**
 * Check if audio is playing (returns 1 if playing, 0 if not)
 */
int32_t qi_gui_audio_is_playing_impl(uint64_t audio_id);

/**
 * Check if audio is finished (returns 1 if finished, 0 if not)
 */
int32_t qi_gui_audio_is_finished_impl(uint64_t audio_id);

/**
 * Free/release an audio player
 */
void qi_gui_audio_free_impl(uint64_t audio_id);

/**
 * Create a renderer for a window
 * Returns renderer ID (> 0) on success, 0 on failure
 */
uint64_t qi_gui_renderer_create_impl(uint64_t window_id);

/**
 * Clear the rendering surface with a color (RGB)
 */
void qi_gui_renderer_clear_impl(uint64_t renderer_id, uint8_t r, uint8_t g, uint8_t b);

/**
 * Draw a filled rectangle
 */
void qi_gui_renderer_draw_rect_impl(uint64_t renderer_id,
                                    uint32_t x,
                                    uint32_t y,
                                    uint32_t width,
                                    uint32_t height,
                                    uint8_t r,
                                    uint8_t g,
                                    uint8_t b);

/**
 * Draw a single pixel
 */
void qi_gui_renderer_draw_pixel_impl(uint64_t renderer_id,
                                     uint32_t x,
                                     uint32_t y,
                                     uint8_t r,
                                     uint8_t g,
                                     uint8_t b);

/**
 * Draw a line using Bresenham algorithm
 */
void qi_gui_renderer_draw_line_impl(uint64_t renderer_id,
                                    int32_t x0,
                                    int32_t y0,
                                    int32_t x1,
                                    int32_t y1,
                                    uint8_t r,
                                    uint8_t g,
                                    uint8_t b);

/**
 * Draw a circle using midpoint circle algorithm
 */
void qi_gui_renderer_draw_circle_impl(uint64_t renderer_id,
                                      int32_t cx,
                                      int32_t cy,
                                      uint32_t radius,
                                      uint8_t r,
                                      uint8_t g,
                                      uint8_t b);

/**
 * Draw an image from file
 * Returns 0 on success, non-zero on error
 */
int32_t qi_gui_renderer_draw_image_impl(uint64_t renderer_id,
                                        const char *file_path,
                                        uint32_t x,
                                        uint32_t y);

/**
 * Resize the renderer surface
 */
void qi_gui_renderer_resize_impl(uint64_t renderer_id, uint32_t width, uint32_t height);

/**
 * Get renderer width
 */
uint32_t qi_gui_renderer_get_width_impl(uint64_t renderer_id);

/**
 * Get renderer height
 */
uint32_t qi_gui_renderer_get_height_impl(uint64_t renderer_id);

/**
 * Free/release a renderer
 */
void qi_gui_renderer_free_impl(uint64_t renderer_id);

/**
 * Draw text at a position with a color
 */
void qi_gui_renderer_draw_text_impl(uint64_t renderer_id,
                                    const char *text,
                                    int32_t x,
                                    int32_t y,
                                    uint8_t r,
                                    uint8_t g,
                                    uint8_t b);

/**
 * Draw text with custom scale
 */
void qi_gui_renderer_draw_text_scaled_impl(uint64_t renderer_id,
                                           const char *text,
                                           int32_t x,
                                           int32_t y,
                                           uint32_t scale,
                                           uint8_t r,
                                           uint8_t g,
                                           uint8_t b);

#endif  /* QI_GUI_H */
